debug_args := -ggdb -pedantic-errors -Wall -Weffc++ -Wextra -Wconversion -Wsign-conversion -Werror

all: double_triple

double_triple: double_triple.cpp
	g++ $(debug_args) -o double_triple double_triple.cpp

clean:
	rm -f double_triple
